config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  get 'welcome/index'
  resources :notes
  
  authenticated :user do
    root 'notes#index', as: "authenticated_root"
  end
  
  root 'welcome#index'

  
  
end

app/models/note.rb
class Note < ActiveRecord::Base
  belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :notes
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/notes_controller.rb
class NotesController < ApplicationController
  before_action :find_note, only: [:show, :edit, :update, :destroy ]
  before_action :authenticate_user!, only: [:new, :create, :edit, :update, :destroy]
  
  def index
    @notes = Note.where(user_id: current_user).order("created_at DESC")
  end
  
  def show
  end
  
  def new
    @note = current_user.notes.build
    @note.user_id = current_user.id
  end
  
  def create
    @user = current_user
    @note = @user.notes.build(note_params)
    @note.user_id = current_user.id
    if @note.save
      redirect_to @note
    else
      render 'new'
    end
  end
  
  def edit
  end
  
  def update
    if @note.update(note_params)
      redirect_to @note
    else
      render 'edit'
    end
  end
  
  def destroy
    if @note.destroy
      redirect_to notes_path
    else
      redirect_to @note
    end
  end


private

def find_note
  @note = Note.find(params[:id])
end

def note_params
  params.require(:note).permit(:title, :content, :user_id)
end

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
    @notes = Note.all.order("created_at DESC")
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/notes_helper.rb
module NotesHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.haml
!!! 
%html
%head
  %title Notenote | Your online notebook
  = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true 
  = javascript_include_tag 'application', 'data-turbolinks-track' => true
  %link{:rel=> "stylesheet", :href=> "//maxcdn.bootstrapcdn.com/font-awesome/4.4.0/css/font-awesome.min.css"}/
  = csrf_meta_tags 

%body
  %header
    .header_inner
      = link_to "Logo", root_path, id: "logo"
      %nav
        - if user_signed_in?
          = link_to "New Note", new_note_path
          = link_to "Sign Out", destroy_user_session_path, method: :delete
        - else
          = link_to "Log In", new_user_session_path
  %p.notice= notice
  %p.alert= alert 

  = yield

app/views/notes/_form.html.haml
= simple_form_for @note do |f|
  = f.input :title
  = f.input :content
  = f.button :submit, class: "button"

app/views/notes/edit.html.haml
.wrapper_with_padding
  
  %h1 Edit note
  
  = render 'notes/form'
  
  = link_to "Cancel", notes_path

app/views/notes/index.html.haml
.wrapper_with_padding
  #notes.clearfix
    - unless @notes.blank?
      - @notes.each do |note|
        %a{ href: (url_for [note])}
          .note
            %p.title= note.title
            %p.date= time_ago_in_words(note.created_at)
    - else 
      %h2 Add a note
      %p It appears you haven't created any notes yet... Let's fix that. Why don't you create a new note below?
      %button= link_to "New Note", new_note_path
      

app/views/notes/new.html.haml
.wrapper_with_padding
  %h1 Add a Note
  
  = render "form"
  
  = link_to "Back", root_path

app/views/notes/show.html.haml
.wrapper_with_padding
  #note_show
    %h1.title= @note.title
    %br
    %p= simple_format(@note.content)
    
  .buttons
    = link_to "Edit", edit_note_path(@note), class: "button"
    = link_to "Delete", note_path(@note), method: :delete, data: { confirm: "Are you sure?" }, class: "button"

app/views/welcome/index.html.haml
#banner
  .banner_content
    %h1 NoteNote
    %p Your online notebook, never forget an idea again.
    %button= link_to "Sign up", new_user_registration_path
#testimonial
  .wrapper
    %p.quote "The greatest notebook application. Period."
    %p.name - Michal Mottl

#callouts
  .callout_inner
    .wrapper
      .callout
        %i.fa.fa-pencil
        %h2 Notes
        %p Vegan skateboard master Vegan skateboard master Dreamcatcher skateboard cray, Dreamcatcher skateboard cray,
      .callout
        %i.fa.fa-rocket
        %h2 Notes
        %p Vegan skateboard master Vegan skateboard master Dreamcatcher skateboard cray, Dreamcatcher skateboard cray,
      .callout
        %i.fa.fa-bolt
        %h2 Notes
        %p Vegan skateboard master Vegan skateboard master Dreamcatcher skateboard cray, Dreamcatcher skateboard cray,
        
#bottom_cta
  .wrapper
    %h2 For Realz!
    %p I want you to sign up!!!
    %button= link_to "Click Meee!", new_user_registration_path
    
%footer
  %p &copy Michal Mottl